spring:        
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                    allowedOrigins: "http://localhost:8281"
                    allowedMethods:
                      -GET
                    allowedHeaders:
                      -Authorization